@VersionManager_HostAddress = http://localhost:5200

POST {{VersionManager_HostAddress}}/weatherforecast/
Accept: application/json
Content-Type: application/json
{
  "name": "test",
  "description": "test description"
}
###
